language: go

go:
  - 1.5.1
  - 1.4.3
  - 1.3.3

before_install:
  - go get golang.org/x/tools/cmd/vet
# maybe one day
#  - go get github.com/golang/lint/golint

sudo: false

script:
  - go vet -x ./...
